-- 1
SELECT MAX(SALARY) FROM hr.employees;
-- 2
SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;
-- 3
SELECT AVG(SALARY) AS average FROM hr.employees
GROUP BY JOB_ID
ORDER BY average DESC;
-- 4
SELECT SUM(SALARY) AS total FROM hr.employees;
-- 5
SELECT ROUND(MAX(SALARY), 2), ROUND(MIN(SALARY), 2), ROUND(SUM(SALARY), 2), ROUND(AVG(SALARY), 2) FROM hr.employees;
-- 6
SELECT JOB_ID, COUNT(*) FROM hr.employees;
-- 7
SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID;
-- 8
SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID LIKE 'IT_PROG';
-- 9
SELECT AVG(SALARY) AS Average, COUNT(*) FROM hr.employees
WHERE JOB_ID NOT LIKE 'IT_PROG'
GROUP BY SALARY
ORDER BY SALARY DESC;
-- 10
SELECT AVG(SALARY) AS Average, COUNT(DEPARTMENT_ID) FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID) >= 10;

-- 11
SELECT PHONE_NUMBER,
	CASE
		WHEN PHONE_NUMBER LIKE '515.%' THEN REPLACE(PHONE_NUMBER, 515, 777)
	END
FROM hr.employees;

-- 12
SELECT * FROM hr.employees
WHERE FIRST_NAME LIKE '________%';

-- 13
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

-- 14
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

-- 15
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

-- 16
SELECT UCASE(FIRST_NAME) FROM hr.employees;

-- 17
SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE HIRE_DATE LIKE '1987-07-%';

-- 18
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM hr.employees
WHERE HIRE_DATE LIKE '1987-07-%';